import { ScanSearch, ShieldCheck, Sparkles } from 'lucide-react';
import Card from '../components/ui/Card.jsx';

export default function About() {
  return (
    <section className="container-page py-16 max-w-3xl">
      <span className="eyebrow">About</span>
      <h1 className="mt-3 text-4xl font-bold tracking-tight">Built to read resumes the way hiring pipelines do.</h1>
      <p className="mt-5 text-lg text-ink/70 dark:text-paper/70 leading-relaxed">
        Most resumes are read by software before they're read by a person. ResumeIQ AI
        surfaces that first pass — the ATS score, the missing keywords, the formatting
        issues — so you can fix them before you hit submit, then rehearse the interview
        that follows.
      </p>

      <div className="grid sm:grid-cols-3 gap-5 mt-10">
        <Card>
          <ScanSearch className="w-6 h-6 text-scan-strong dark:text-scan mb-3" />
          <h3 className="font-semibold mb-1.5">AI-powered</h3>
          <p className="text-sm text-ink/65 dark:text-paper/65">Every analysis is generated by Google's Gemini model in real time — no templated scoring.</p>
        </Card>
        <Card>
          <ShieldCheck className="w-6 h-6 text-scan-strong dark:text-scan mb-3" />
          <h3 className="font-semibold mb-1.5">Nothing stored</h3>
          <p className="text-sm text-ink/65 dark:text-paper/65">No database, no accounts. Your resume and results live only in your current browser session.</p>
        </Card>
        <Card>
          <Sparkles className="w-6 h-6 text-scan-strong dark:text-scan mb-3" />
          <h3 className="font-semibold mb-1.5">End to end</h3>
          <p className="text-sm text-ink/65 dark:text-paper/65">From ATS score to cover letter to interview prep — one flow, no juggling five separate tools.</p>
        </Card>
      </div>

      <div className="mt-12 surface p-8">
        <h2 className="text-xl font-semibold mb-3">Why this project exists</h2>
        <p className="text-sm text-ink/70 dark:text-paper/70 leading-relaxed">
          ResumeIQ AI was built as a final-year computer science portfolio project — an
          exercise in shipping a full AI product end to end: a React frontend, an
          Express API, LLM integration, file parsing, and PDF generation, all without
          leaning on a database or auth system to do the heavy lifting.
        </p>
      </div>
    </section>
  );
}
